Update GFDL compiler settings from Intel to GCC
NOAA-GFDL/FRE-NCtools pull request #153
Opened 2022-04-21 21:36 UTC by ceblanton

#99

2022-04-21 21:37 UTC, ceblanton commented
@ngs333 I tested the 3 configs and they all compiled and passed tests (except for the omgg). However, I have zero build options which is probably not right, and I don't know what we want.

2022-04-22 17:04 UTC, ngs333 commented on site-configs/ncrc/config.site
> -test -z "$CFLAGS" && CFLAGS="-xSSE2"
Chris, The Intel default optimization flag is -O2. The GNU default optimization flag is -O0.
So we need to add the -O2 flag whenever we use gcc. Thats for both CFLAGS and FCFLAGS.

2022-04-22 17:05 UTC, ngs333 requested changes
The Intel default optimization flag is -O2. The GNU default optimization flag is -O0.
So we need to add the -O2 flag whenever we use gcc. Thats for both CFLAGS and FCFLAGS.

2022-04-27 22:27 UTC, ngs333 approved these changes

2022-04-28 19:20 UTC, ngs333 approved these changes

2022-05-05 13:49 UTC, merged