Remove bats from remaining tests
NOAA-GFDL/FRE-NCtools pull request #331
Opened 2024-12-11 19:49 UTC by underwoo

Migrate the remaining tests in the "t" directory to not depend on bats.

Many of the remaining tests are slower (expensive) tests.  There will be a way for the developer to run the expensive and very-expensive tests.  They will be skipped by default.

Fixes # (issue)

**How Has This Been Tested?**
Please describe the tests that you ran to verify your changes. Please also note
any relevant details for your test configuration (e.g. compiler, OS).  Include
enough information so someone can reproduce your tests.

**Checklist:**
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] New check tests, if applicable, are included
- [ ] `make distcheck` passes

2025-01-07 12:43 UTC, mlee03 requested changes

2025-01-07 12:43 UTC, mlee03 commented on tests/create_daily_tile_files.c
> +#include <stdio.h>
Does it need the license info?

2025-01-07 12:45 UTC, mlee03 commented
@rem1776, any chance you could review this PR by end of this week?

2025-01-08 18:18 UTC, underwoo commented on tests/fregrid/remap-file-mpi
> +"${top_srcdir}"/tests/nc_cmp -md fregrid_remap_file_640_by_400.nc fregrid_remap_file_640_by_400-mpi.nc \
They are passing on my Mac and my home Linux system.  This test is not run in the CI/CD tests, as this is marked as "expensive".  

After this is merged, this test will be run in one of the new CI/CD workflows.

2025-01-13 20:48 UTC, ceblanton approved these changes
Thank you Seth. These changes remove the dependency on bats and also improves the input test file creation and makes the test script and directories more consistent.

2025-01-13 21:07 UTC, mlee03 approved these changes

2025-01-13 22:08 UTC, merged