Use newer gcc in GFDL env.sh files to handle the new _Generic type handling
NOAA-GFDL/FRE-NCtools pull request #38
Opened 2021-01-12 18:01 UTC by ceblanton

closes #37

2021-01-13 18:11 UTC, underwoo requested changes
I think it would be better to modify this to use the new spack installed software.  I have the following for the gfdl workstations

```
# **********************************************************************
# Setup and Load the Modules
# **********************************************************************
source /usr/local/Modules/default/init/sh
module use /app/spack/modulefiles/linux-rhel7-x86_64
module load intel_compilers/18.0.5
module load netcdf-c/4.6.1-intel-18.0.5
module load netcdf-fortran/4.4.4-intel-18.0.5
module load mpich/3.2.1-intel-18.0.5
# GCC is needed for icc to use newer C11 constructs
module load gcc/9.2.0-gcc-4.8.5

# Add bats to PATH
PATH=${PATH}:/home/sdu/opt/bats/bin
export PATH

# **********************************************************************
# Set environment variablesSetup and Load the Modules
# **********************************************************************
# The GCC module sets CC and FC to gcc.  Since we want to use icc/ifort
# we will change CC and FC (and a few others)
FC=ifort
CC=icc
F77=ifort
CXX=icpc
export FC CC F77 CXX
```

I haven't pushed it yet as I was attempting to get all the tests to pass -- Tests 22,23,24,25 and 26 are failing for me.

2021-03-04 22:11 UTC, ngs333 approved these changes

2021-03-09 17:00 UTC, ceblanton commented
@underwoo could you take another look at these GFDL and GFDL-WS env.sh updates? They have almost all of yours gfdl-ws updates.

2021-03-12 00:42 UTC, ceblanton commented
closing this, will reopen with @underwoo's complete env.sh updates

2021-03-12 00:42 UTC, closed without merging