Enable telescoping nests (multiple levels)
NOAA-GFDL/FRE-NCtools pull request #63
Opened 2021-03-05 23:52 UTC by JosephMouallem

These modifications will allow multiple telescoping nests functionality.
Telescoping nests are defined as nests within nests.
This works for many nest levels.

2021-03-08 15:43 UTC, bensonr approved these changes

2021-03-08 16:19 UTC, ngs333 commented
@JosephMouallem , 
I am approving this PR, but do you think a unit test (directoryy  FRE-NCtools/t ) should be added or modified to cover the changes you introduced?

2021-03-08 16:20 UTC, ngs333 approved these changes

2021-03-08 20:41 UTC, ngs333 commented
@JosephMouallem Do you already have the tests? If so, do you need help in adding them?

2021-03-09 16:49 UTC, ceblanton approved these changes
Looks good, and agree a test should be added

2021-03-11 16:33 UTC, ngs333 commented
@JosephMouallem 
Joseph, just letting you know I'll wait for the unit tests prior to merging this PR.
There was a discussion on whether to merge now and latter merge the unit test under a different github issue,
but it was decided to hold the merge.  Thanks

2021-03-11 21:11 UTC, JosephMouallem commented
@ngs333 Hi Miguel,
I added a file that tests for the generation of same level and telescoping nests, let me know if this works.

2021-03-12 16:23 UTC, ceblanton commented on t/Test27-multiple_nests.sh
> +		--nest_grids 3 \
Hi @JosephMouallem `--nest_grids` should be singular, `--nest_grid` here and below in line 66

2021-03-12 16:27 UTC, ceblanton commented
Hi @JosephMouallem could you please merge your branch with the updated master, and push back? We have fixed a failing test recently that should allow your tests to pass on the github CI (also, the make_grid option `--nest_grids` should be `--nest_grid`)

2021-03-12 21:18 UTC, ngs333 commented
@JosephMouallem 
I think the only thing missing is to add the name of the test shell script to the Makefile.am in directory t.
If you do that then we can automatically run it in as one of the tests in the suite of unit tests. For example, if you run "make check" after you run "make", then you will see  all the unit tests run, including yours. Its just one line to add, once you are done, the middle of Makefile.am should look like this:

        Test26-reference_fregrid_gcc.sh \
	Test27-multiple_nests.sh \
        01-make_hgrid.sh \
        01-make_vgrid.sh

2021-03-12 21:20 UTC, ngs333 requested changes
See comment on Makefile.am.

2021-03-13 00:43 UTC, JosephMouallem commented
@ceblanton Hi Chris, I don't think --nest_grid is working anymore (the code doesn't fail but it only creates one additional grid if used). To create the multiple nests --nest_grids should be used with an argument (number of nests). If this creates issues in the future, we can add a reference directory to make sure we are doing the right thing.

@ngs333 Miguel, please see the updated Makefile.am, I think it is working correctly.

Thanks!

2021-03-15 15:03 UTC, ngs333 approved these changes

2021-03-15 15:07 UTC, merged