Updated build instructions for GFDL sites using "eval `env.sh`" usage
NOAA-GFDL/FRE-NCtools pull request #77
Opened 2021-04-09 14:00 UTC by ceblanton

Closes #75

2021-04-09 15:27 UTC, ngs333 commented
I've noticed that some folks do not immediately notice that the quotes are single forward and not something else.  Do you think it might be a good idea to someplace sneak in a word/text hint about this?

2021-04-09 15:45 UTC, ceblanton commented
Thanks, great point! Both the backquotes and the eval could use a note of explanation. I added an explanation directly above the `eval` for simplicity (it could go someplace else)

2021-04-22 00:26 UTC, underwoo requested changes

2021-04-22 00:26 UTC, underwoo commented on README.md
> +located in the [site-configs](site-configs) directory:
Suggested change:

```
If building on a GFDL-managed system, the recommended environment with the recommended autoconf defaults can be loaded by running the output generated by the site-specific `env.sh` script, located in the [site-configs](site-configs) directory:
```

2021-04-23 13:38 UTC, ceblanton commented on README.md
> +located in the [site-configs](site-configs) directory:
Updated, thanks Seth

2021-04-23 14:53 UTC, ngs333 approved these changes

2021-04-23 15:49 UTC, merged